// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FundStatus string

const (
	FundStatusFundraising FundStatus = "fundraising"
	FundStatusInvesting   FundStatus = "investing"
	FundStatusClosed      FundStatus = "closed"
)

func (e *FundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FundStatus(s)
	case string:
		*e = FundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FundStatus: %T", src)
	}
	return nil
}

type NullFundStatus struct {
	FundStatus FundStatus
	Valid      bool // Valid is true if FundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FundStatus), nil
}

type InvestorType string

const (
	InvestorTypeIndividual   InvestorType = "individual"
	InvestorTypeInstitution  InvestorType = "institution"
	InvestorTypeFamilyoffice InvestorType = "family office"
)

func (e *InvestorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvestorType(s)
	case string:
		*e = InvestorType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvestorType: %T", src)
	}
	return nil
}

type NullInvestorType struct {
	InvestorType InvestorType
	Valid        bool // Valid is true if InvestorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvestorType) Scan(value interface{}) error {
	if value == nil {
		ns.InvestorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvestorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvestorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvestorType), nil
}

type Fund struct {
	ID            pgtype.UUID        `db:"id"`
	Name          string             `db:"name"`
	VintageYear   int32              `db:"vintage_year"`
	TargetSizeUsd pgtype.Numeric     `db:"target_size_usd"`
	Status        FundStatus         `db:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

type Investment struct {
	ID             pgtype.UUID    `db:"id"`
	InvestorID     pgtype.UUID    `db:"investor_id"`
	FundID         pgtype.UUID    `db:"fund_id"`
	AmountUsd      pgtype.Numeric `db:"amount_usd"`
	InvestmentDate pgtype.Date    `db:"investment_date"`
}

type Investor struct {
	ID           pgtype.UUID        `db:"id"`
	Name         string             `db:"name"`
	InvestorType InvestorType       `db:"investor_type"`
	Email        string             `db:"email"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
}
