// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFund = `-- name: CreateFund :one
INSERT INTO fund (id, name, vintage_year, target_size_usd, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, vintage_year, target_size_usd, status, created_at
`

type CreateFundParams struct {
	ID            pgtype.UUID        `db:"id"`
	Name          string             `db:"name"`
	VintageYear   int32              `db:"vintage_year"`
	TargetSizeUsd pgtype.Numeric     `db:"target_size_usd"`
	Status        FundStatus         `db:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error) {
	row := q.db.QueryRow(ctx, createFund,
		arg.ID,
		arg.Name,
		arg.VintageYear,
		arg.TargetSizeUsd,
		arg.Status,
		arg.CreatedAt,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUsd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investment (id, investor_id, fund_id, amount_usd, investment_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, investor_id, fund_id, amount_usd, investment_date
`

type CreateInvestmentParams struct {
	ID             pgtype.UUID    `db:"id"`
	InvestorID     pgtype.UUID    `db:"investor_id"`
	FundID         pgtype.UUID    `db:"fund_id"`
	AmountUsd      pgtype.Numeric `db:"amount_usd"`
	InvestmentDate pgtype.Date    `db:"investment_date"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.ID,
		arg.InvestorID,
		arg.FundID,
		arg.AmountUsd,
		arg.InvestmentDate,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.InvestorID,
		&i.FundID,
		&i.AmountUsd,
		&i.InvestmentDate,
	)
	return i, err
}

const createInvestor = `-- name: CreateInvestor :one
INSERT INTO investor (id, name, investor_type, email, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, investor_type, email, created_at
`

type CreateInvestorParams struct {
	ID           pgtype.UUID        `db:"id"`
	Name         string             `db:"name"`
	InvestorType InvestorType       `db:"investor_type"`
	Email        string             `db:"email"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateInvestor(ctx context.Context, arg CreateInvestorParams) (Investor, error) {
	row := q.db.QueryRow(ctx, createInvestor,
		arg.ID,
		arg.Name,
		arg.InvestorType,
		arg.Email,
		arg.CreatedAt,
	)
	var i Investor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvestorType,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getFundByID = `-- name: GetFundByID :one
SELECT id, name, vintage_year, target_size_usd, status, created_at FROM fund WHERE id = $1
`

func (q *Queries) GetFundByID(ctx context.Context, id pgtype.UUID) (Fund, error) {
	row := q.db.QueryRow(ctx, getFundByID, id)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUsd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvestorByEmail = `-- name: GetInvestorByEmail :one
SELECT id, name, investor_type, email, created_at FROM investor WHERE email = $1
`

func (q *Queries) GetInvestorByEmail(ctx context.Context, email string) (Investor, error) {
	row := q.db.QueryRow(ctx, getInvestorByEmail, email)
	var i Investor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvestorType,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getInvestorByID = `-- name: GetInvestorByID :one
SELECT id, name, investor_type, email, created_at FROM investor WHERE id = $1
`

func (q *Queries) GetInvestorByID(ctx context.Context, id pgtype.UUID) (Investor, error) {
	row := q.db.QueryRow(ctx, getInvestorByID, id)
	var i Investor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InvestorType,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listFunds = `-- name: ListFunds :many
SELECT id, name, vintage_year, target_size_usd, status, created_at FROM fund ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListFundsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListFunds(ctx context.Context, arg ListFundsParams) ([]Fund, error) {
	rows, err := q.db.Query(ctx, listFunds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fund
	for rows.Next() {
		var i Fund
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VintageYear,
			&i.TargetSizeUsd,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestmentsByFundID = `-- name: ListInvestmentsByFundID :many
SELECT id, investor_id, fund_id, amount_usd, investment_date FROM investment WHERE fund_id = $1
`

func (q *Queries) ListInvestmentsByFundID(ctx context.Context, fundID pgtype.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByFundID, fundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.InvestorID,
			&i.FundID,
			&i.AmountUsd,
			&i.InvestmentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestors = `-- name: ListInvestors :many
SELECT id, name, investor_type, email, created_at FROM investor ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListInvestorsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListInvestors(ctx context.Context, arg ListInvestorsParams) ([]Investor, error) {
	rows, err := q.db.Query(ctx, listInvestors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investor
	for rows.Next() {
		var i Investor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InvestorType,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFund = `-- name: UpdateFund :one
UPDATE fund
SET name = $2, vintage_year = $3, target_size_usd = $4, status = $5
WHERE id = $1
RETURNING id, name, vintage_year, target_size_usd, status, created_at
`

type UpdateFundParams struct {
	ID            pgtype.UUID    `db:"id"`
	Name          string         `db:"name"`
	VintageYear   int32          `db:"vintage_year"`
	TargetSizeUsd pgtype.Numeric `db:"target_size_usd"`
	Status        FundStatus     `db:"status"`
}

func (q *Queries) UpdateFund(ctx context.Context, arg UpdateFundParams) (Fund, error) {
	row := q.db.QueryRow(ctx, updateFund,
		arg.ID,
		arg.Name,
		arg.VintageYear,
		arg.TargetSizeUsd,
		arg.Status,
	)
	var i Fund
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VintageYear,
		&i.TargetSizeUsd,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
